export const tarot = {
  debut: {
    label: "the debut",
    danceability: 5,
    energy: 20,
    loudness: 20,
    popularity: 2,
  },
  artist: {
    label: "the artist",
    danceability: 2,
    energy: 5,
    loudness: 20,
    popularity: 15,
  },
  songWriter: {
    label: "the song writer",
    danceability: 15,
    energy: 10,
    loudness: 5,
    popularity: 20,
  },
  producer: {
    label: "the producer",
    danceability: 30,
    energy: 30,
    loudness: 30,
    popularity: 20,
  },
  beat: {
    label: "the beat",
    danceability: 33,
    energy: 33,
    loudness: 25,
    popularity: 20,
  },
  bassist: {
    label: "the bassist",
    danceability: 20,
    energy: 25,
    loudness: 20,
    popularity: 33,
  },
  duet: {
    label: "the duet",
    danceability: 3,
    energy: 20,
    loudness: 5,
    popularity: 10,
  },
  guitarist: {
    label: "the guitarist",
    danceability: 25,
    energy: 30,
    loudness: 33,
    popularity: 33,
  },
  singer: {
    label: "the singer",
    danceability: 15,
    energy: 25,
    loudness: 30,
    popularity: 33,
  },
  soloist: {
    label: "the soloist",
    danceability: 15,
    energy: 5,
    loudness: 6,
    popularity: 22,
  },
  shuffle: {
    label: "shuffle",
    danceability: 30,
    energy: 25,
    loudness: 20,
    popularity: 33,
  },
  drummer: {
    label: "the drummer",
    danceability: 33,
    energy: 33,
    loudness: 33,
    popularity: 10,
  },
  interlude: {
    label: "the interlude",
    danceability: 1,
    energy: 1,
    loudness: 1,
    popularity: 1,
  },
  outro: {
    label: "the outro",
    danceability: 1,
    energy: 5,
    loudness: 5,
    popularity: 1,
  },
  harmony: {
    label: "harmony",
    danceability: 5,
    energy: 10,
    loudness: 15,
    popularity: 10,
  },
  triTone: {
    label: "the tri-tone",
    danceability: 1,
    energy: 1,
    loudness: 15,
    popularity: 15,
  },
  keyChange: {
    label: "the key change",
    danceability: 2,
    energy: 30,
    loudness: 10,
    popularity: 25,
  },
  icon: {
    label: "the icon",
    danceability: 33,
    energy: 33,
    loudness: 20,
    popularity: 33,
  },
  flop: {
    label: "the flop",
    danceability: 1,
    energy: 1,
    loudness: 1,
    popularity: 1,
  },
  chorus: {
    label: "the chorus",
    danceability: 33,
    energy: 12,
    loudness: 14,
    popularity: 33,
  },
  verse: {
    label: "the verse",
    danceability: 8,
    energy: 8,
    loudness: 15,
    popularity: 10,
  },
  launch: {
    label: "the launch",
    danceability: 27,
    energy: 11,
    loudness: 20,
    popularity: 30,
  },
};
